default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.3
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [manual]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.18
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
        args: [--unsafe]
        exclude: ^helm/
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args: [--chart-search-root=helm, --template-files=README.md.gotmpl]

  - repo: local
    hooks:
      - id: ty-check
        name: ty check
        entry: uv run ty check aperture tests
        language: system
        pass_filenames: false
        types_or: [python, pyi]
      - id: helm-lint
        name: helm lint
        entry: helm lint helm/aperture
        language: system
        pass_filenames: false
        files: ^helm/
      - id: helm-template
        name: helm template
        entry: helm template aperture helm/aperture
        language: system
        pass_filenames: false
        files: ^helm/
      - id: helm-unittest
        name: helm unittest
        entry: helm unittest --strict helm/aperture
        language: system
        pass_filenames: false
        files: ^helm/
